### ISSUE TITLE
Pick language and technology stack for the project

### ISSUE THREAD

**Issue by nejdaw** [Viridovix/show-me-the-code-github#6]
We need to pick technologies that we can use to build our plugin. Particularly we need to choose:
- language
- build tool
- testing framework (unit / system tests)

This story depends on the outcome of #5

**Comment by nejdaw** [comment]
My proposition: **[Babel](https://babeljs.io/)**

Language: ECMAScript 6 (newest version of JavaScript)
Build tool: [WebPack](https://webpack.github.io/)
Compiler: Babel (compiles ECMAScript 6 to ECMAScript 5)
Testing framework: [Mocha](https://mochajs.org/), [Karma](http://karma-runner.github.io/0.13/index.html)

Sample chrome extension using Babel: https://github.com/schovi/webpack-chrome-extension

**Comment by balawama** [comment]
Language:
- Dart (https://www.dartlang.org/) 
- CoffeeScript II (https://github.com/michaelficarra/CoffeeScriptRedux)

Build tool: 
- Pub (https://www.dartlang.org/tools/pub/get-started.html)
- Brunch (http://brunch.io/)

Testing:
- Dart based (https://pub.dartlang.org/packages/test)
- Beast (http://beastjavascript.github.io/TestSuite/)

**Comment by nejdaw** [comment]
Some people consider coffee script to be less relevant in when they can use ES6 ([source](https://github.com/coffeescript-cookbook/coffeescript-cookbook.github.io/issues/128)). 

Dart, on the other hand, seems to be an interesting idea.

**Comment by mkordas** [comment]
My proposition is ScalaJS with SBT - it's the technology I'd like to learn anyway.

**Comment by nejdaw** [comment]
OK, so the final decision is Babel.

**Comment by balawama** [comment]
What about build tool? Do we want to raise new issue for that?

**Comment by nejdaw** [comment]
@balawama I did some digging and I think that WebPack will be sufficient as a build tool. So to summarise:
1. Runtime environment: node.js
2. Compiler: babel
3. Build tool: webpack
4. Tests: lets start with Mocha and then replace it if something is wrong

This issue is closed but I will create new issue to set up sample project with stub js file and sample test

**Comment by nmccready** [comment]
Not really my business but webpack has some serious issues with css sourcemaps . Thought I might save you the pain.

https://github.com/webpack/style-loader/issues/55
https://github.com/webpack/css-loader/issues/29

We switched to browserify which still is not perfect as debugging coffeescript in the browser stinks. (that was easier to handle in webpack)

IE browserify problem. https://github.com/substack/node-browserify/issues/1233

Browserify/Webpack also integrates quite nicely into brunch.io as well. Also gulp works well with either too. But if you go gulp use 4.0 branch.. way easier.

https://www.npmjs.com/package/browserify-brunch

**Comment by nejdaw** [comment]
Hi @nmccready 
Thanks for contribution! 

We will consider it when we finally find some time to work on the project.
